name: Build & publish to PyPI
on:
  push:
    tags: ["v*"]          # every Git tag like v0.2.0 triggers
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with: {python-version: '3.x'}
    - name: Build wheel & sdist
      run: |
        python -m pip install build
        python -m build --sdist --wheel --outdir dist
    - uses: actions/upload-artifact@v4
      with: {name: python-package-distributions, path: dist/}

  publish-to-pypi:
    needs: build
    runs-on: ubuntu-latest
    permissions: {id-token: write, contents: read}  # for trusted publishing
    steps:
    - uses: actions/download-artifact@v4
      with: {name: python-package-distributions, path: dist/}
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
