name: tests

on:
  push:
    branches: [develop, main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"

    - name: Install package + dev extras
      run: |
        python -m pip install --upgrade pip
        pip install ".[dev]"

    - name: Run unit tests
      run: |
        pytest -ra --cov=searchpubmed --cov-report=xml

    # ---- OPTIONAL: upload coverage ----
    - name: Upload coverage to Codecov
      if: github.repository_owner == 'OHDSI'
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
